### ISSUE TITLE
ATK et DEF issue

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/HOI4_Calculator#39]
1.  Les stats des unités (sans armes) soient en accord avec les stats approximatives de HOI 4 (voir https://github.com/Florian-DELRIEU/HOI4_Calculator/issues/39#issuecomment-1012510731 )

2. Faire en sorte que les armes donne un bonus (multilicateur) des ces stats aux unités qui le composent 
  Ex : 
        - 1 compagnie de 100 gardes ( `DEF=20`, `ATK=2`)
        - 100 fusil laser  ( `Tir rapide => No bonus`  )
        - 5 Shotgun ( `Assaut => *1.05` par exemple

## TODO 
- [x] Changer les bonus d'ATK DEF des armes en par des multiplicateur en fonction de leurs type
- [x] Revoir ATK/DEF pour les infantry (en accord avec HOI4 ?)
- [x] Revoir ATK/DEF pour les véhicules
- [x] Voir ATK/DEF pour les Marcheurs 
- [x] DEF/BRK bonuses for grenades ?
- [x] Regler les bonus DEF/BRK pour les armes dans les chars (Turret,Side,Hull)
- [x] Change SMA and HMA stats 

## Validations de STATS
- [x] DEF/BRK Pour toutes les unités et companies
- [x] Equilibrer SA HA pour tank (trop faible par rapport a  infantry)

**Comment by Florian-DELRIEU** [comment]
## DEFENSE & BREAKTRHOUGHT
### Infantry and Infantry mobile bataillon
|       Weapons       | Defense | Breakthrought |
|:-------------------:|:-------:|:-------------:|
|       Infantry      |  20-22  |      2-3      |
| Motorized Infantry |  20  |      2      |
|       Cavalry      |    20-22    |       2-3       |
| Mechanized Infantry |  46-48  |      6-7      |

### Equipement and SP Equipement
| Weapons | Defense | Breakthrought |
|:---:|:---:|:---:|
| AA | 4 | 1 |
| AT | 4 | 0 |
| Artillery | 10-12 | 6-9 |
| Destroyer | 4-5-4-7-8 | 1-1.3-1-1.8-2 |
| SP Artillery | 4-5-4-7-8 | 2-3-2-3.5-4 |
| SP AA | 2-2.5-2-3.5-4 | 2-2.5-2-3.5-4 |

### Armored
| Weapons | Defense | Breakthrought |
|:---:|:---:|:---:|
| Armored Car | 2 | 12 |
| Light | 4 | 26 |
| Medium | 5 | 36 |
| Heavy | 6 | 36 |
| Super Heavy | 10 | 74 |
| Modern | 10 | 84 |
