### ISSUE TITLE
GUI - GENERAL TODO LIST

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/HOI4_Calculator#57]
# Land Battle Window
## Logs
- [ ] Afficher ou pas les logs
- [ ] Choisir niveau de détail des logs

## Divisions
- [ ] Fenêtre flottante montrant les stats entière d'une division
- [ ] Améliorer affichage division
- [x] Améliorer ajout d'une division
- Pouvoir copier une division

##  Interface
- [ ] Choisir le nombre de rounds à lancer
- [x] Nommer les camps 
- [ ] Barre de victoire
- [ ] Choisir météo 
- [ ] Choisir le Terrain 
- [x] Choisir les Leaders 
- [x] Choisir les Tactiques 

## Mécanique de combat
- [x] Round d'initiative (Choix du perdant et tentative de contre du gagnant)
- [x] Désignation des division sur la ligne de front et aux réserves
- [x] Désignation des cibles au début
- [x] Changement de cible 
- [x] Nombre d'attaque et dégâts sur division
- [x] Tour de l'attaquant
- [x] Riposte du défenseur
- [x] Déplacement en réserves si ORG ou PV a 0
- [x] Renforts depuis reserves 
- [ ] Couts en supplies ?

## Autre mécanique de combat
https://hoi4.paradoxwikis.com/Land_battle#:~:text=The%20following%20factors,22%5D%20intel%20advantage
- [x] Tactiques
- [x] Leader
  - [x] Compétence
  - [ ] Planification
- [ ] Météo
- [x] Terrain
  - [x] Traversé de rivière
  - [x] Encerclement
  - [x] Forts
  - [x] Retranchement
  - [ ] Combat depuis plusieurs front
  - [ ] Nuit
- [ ] Mouvement (effet sur la bataille ?)
- [ ] Aviation
- [ ] Dégats collateraux
- [x] Expérience des divisions
- [x] Penalité de cumul de divisions
- [ ] Bonus de nations
- [ ] Avantage de renseignement
- Pénalité de combat
  - [ ] Manque de ravitaillement 
  - [ ] Parachutage
  - [ ] Débarquement
- [ ]  Maréchaux 
  - [ ] Ajouter les habilités stratégiques (Assaut intensif, Dernier debouts)

## Gestion des sauvegardes
- [ ] Pouvoir sauvegarder une bataille 
- [ ] Charger une bataille
- [x] Sauvegarder / charger divisions
