### ISSUE TITLE
GUI 3.1.X - TODO LIST

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/HOI4_Calculator#58]
## Objectif
Implémenter les bases du combats entre plusieurs divisions (sans effets extérieurs comme le terrain, les leaders, la météo, la supériorité aérienne)
Il faut que les division puissent s'engager, se battre et recevoir des dégâts, et se désengager ou battre en retraite 

- [x] Ajouter liste pour les divisions actives en bataille
- [x] Gérer engagement des divisions en fonction de l'aire de combat
- [x] Verifier que le width d'une division ne dépasse pas la limite avant de faire la sélection
- [x] Mécanique de combat (round attaque - dommage)
- Acquisition de nouvelles cibles et changement de cibles
- [x] Riposte du défenseur
- [x] retrait de la bataille si ORG ou PV a 0
- [x] Renforts depuis reserves 

### Sources
- https://hoi4.paradoxwikis.com/Land_battle

**Comment by Florian-DELRIEU** [comment]
# Combat width

![IMG_20240804_024556.jpg](https://github.com/user-attachments/assets/b5e552f3-aa12-4d64-93a7-68e06196bc7c)

**Comment by Florian-DELRIEU** [comment]
# Reserves

![chrome_screenshot_4 août 2024 02_48_59 GMT+02_00.png](https://github.com/user-attachments/assets/575f98d7-2675-4674-9306-7ee521d0e1e3)
