### ISSUE TITLE
GUI 3.2.X - Todo list

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Florian-DELRIEU/HOI4_Calculator#62]
- [x] Assigner les tactic_bonus_damages aux divisions dans les listes frontlines uniquement
- [x] Incorporer les battle phases
- [x] Ajouter tout les triggers pour les tactiques
  - [x] Ajouter les traits
- [x] Ajouter les bonus sur les largeur de combats
- Vérifier pénalité de mouvements
  - Influence sur le combat ou non ? si oui ajouter la mécanique
- [x] Ajouter les nouvelles tactiques
- [x] Mettre a jour la mécanique de renforts en fonctions des modifications de combat_width
- [x] Ajouter les malus lors de dépassement de largeur de combat 
- [x] Choisir les Tactiques
- [x] trouver l'influence explicite des leaders sur l'initiative
- Retirer le bonus de coordination dues au compétences des généraux (Amiral uniquement)
- [x] Expériences et ses effets
- [x] Retranchement 
- [x] Interface graphique pour leaders
- [x] Faire vérifier les nouvelles fonctions par GPT
- [x] Verifier que les effets des leaders soient mise en jour dès le choix des leaders
- [x] Ajouter des leaders par défaut et les afficher
